<!DOCTYPE html>
<html lang="fr">
<head>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/lightbox.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> <?= ucfirst("Histoire") ?> </title>
</head>
<body>
  <?php include ROOT_PATH."/view/inc/header.php" ?>  
<div class="wrapper">
 <?php include ROOT_PATH."/view/inc/menu.php"?>
<div class="contenu-page">

    <h2 class="titre-page">Histoire</h2>

    <div class="img-centree">
        <img src="img/histoire.jpg" alt="Vue de Berlin">
    </div>

    <h3>Origines</h3>
    <p>Les silex taillés et les outils en os retrouvés lors de fouilles permettent de faire remonter la présence humaine dans la région de Berlin à 60 000 av. J.-C. À cette époque, la plus grande partie du Nord et de l'Est de l'Allemagne actuelle est couverte par les glaciers de la glaciation vistulienne, qui s'étend de 70 000 à 8 000 av. J.-C. Le point le plus méridional de l'inlandsis est alors à 75 km au sud de Berlin, où prend naissance la vallée proglaciaire de Głogów-Baruth (Glogau-Baruther Urstromtal). L'habitat se confine aux plateaux élevés épargnés par les glaces. Vers -18 000 les derniers glaciers creusent en se retirant depuis Francfort-sur-l'Oder la vallée proglaciaire de Varsovie-Berlin (Warschau-Berliner-Urstromtal), qui comporte un sandur très épais. Vers -16 000, le site de Berlin, libre de glaces, est une moraine. Une rivière, la Spree, établit à présent son cours dans la vallée glaciaire, avec à l'aval une toundra couverte de pinèdes. À l'ouest, des dépressions humides et des zones marécageuses confèrent son aspect à la vallée entière.
À la suite de la péjoration climatique qui sévit entre le IVe et le Ve siècle de notre ère, les Semnons abandonnent une grande partie des plaines entre la Havel et la Spree pour s'établir dans la vallée supérieure du Rhin, en Souabe. Le Brandebourg se dépeuple, mais reste un territoire peuplé de Germains jusqu'à ce qu'au vie siècle, des peuples slaves immigrent par vagues successives en Lusace ; ils atteignent la haute vallée de la Spree en 720, occupent les anciens sites germains et fondent dans tout le pays de nouveaux villages souvent lacustres.

En 1157, le prince allemand Albrecht l’Ours inflige au prince slave Jaxa de Copnic, alors au sommet de sa force, une défaite décisive, qui permet la fondation de la marche de Brandebourg. Celle-ci inaugure l'assimilation (germanisation et christianisation) des Slaves (à l'exception des Sorabes, christianisés plus tard, et qui ont gardé leur langue slave jusqu'à nos jours). La construction des premiers quartiers de Berlin coïncide avec la fondation du margraviat de la maison d'Ascanie à Teltow, et elle est marquée par une politique de colonisation habile (avec intégration de l'aristocratie slave antérieure) et une collaboration active avec les moines cisterciens du monastère de Lehnin. Le quartier du Zehlendorf, au sud de Berlin, et au-delà le village slave de Slatdorp sur le lac de Slatsee (auj. Schlachtensee (de)) ressortissaient du domaine ecclésiastique de Lehnin.

    </p>

    <h3>Fondation de Berlin
</h3>
    <p>Entre le plateau de Teltow méridional et le plateau de Barnim septentrional, les berges asséchées d'un gué de la vallée proglaciaire marécageuse sont d'abord colonisées. Quelques-uns des faubourgs qui deviendront plus tard des quartiers de Berlin sont mentionnés dès le XIIe siècle : Spandau en 1197, Köpenick en 1209, Cölln en 1237 et Berlin en 1244. Tempelhof désigne une commanderie de Templiers. Cölln est une île de la Spree, tandis que Berlin s'étend sur la rive droite. Spandau et Köpenick sont des villages slaves préexistants à la conquête. Spandau obtient une charte communale en 1232, et Berlin très probablement à la même date. Berlin et Cölln fusionnent en 1307. Grâce au privilège accordé par le gouvernement bicéphale des margraves Othon III de Brandebourg et Jean Ier de Brandebourg, la ville unifiée Berlin-Cölln peut alors s'imposer économiquement aux villes conquises de Spandau et Köpenick.

Des recherches récentes montrent que Cölln et Berlin existaient en fait très probablement déjà dans le dernier tiers du XIIe siècle. Le développement et les privilèges accordés à la double ville par les deux margraves au cours des années 1230 paraissent liés à la colonisation des plateaux de Teltow et Barnim. La ville et ses remparts étaient stratégiquement importants pour contrer les entreprises des seigneurs de Wettin sur le mont Teltow, le Köpenick et la forêt du Mittenwald, ainsi que pour s'opposer à la création d'un nouveau fief autour de Hönow (de) (incluant, entre autres, Hellersdorf). La frontière séparant la marche d'Ascanie et les fiefs des Wettin courait selon un axe nord-sud à peu près au milieu de l'actuelle Berlin. Le contentieux avec les Wettin fut tranché lors de la guerre de Teltow (de) entre 1239 et 1245 : les seigneurs d'Ascanie, vainqueurs, obtinrent la cession des plateaux de Teltow et de Barnim (à l'exception du village de Rüdersdorf) et ainsi la totalité des territoires sur lesquels la ville s'étend de nos jours.

    </p>

    <h3>Le royaume de Prusse
</h3>
    <p>En récompense de son ralliement à la cause autrichienne au début de la guerre de Succession d'Espagne, le prince-électeur Frédéric III obtint l'élévation de son margraviat au rang de royaume. Il se fit couronner en 1701 à Königsberg, capitale de Prusse, sous le nom de Frédéric Ier roi en Prusse (et non pas de Prusse, car il n'était pas souverain de toute la Prusse historique, une partie se trouvant encore en Pologne-Lituanie, hors du Saint-Empire romain germanique). Frédéric Ier était un souverain qui se voyait principalement comme le serviteur de son État. Il fit construire le château de Charlottenburg à l'ouest de Berlin, et ce château fut promu en 1707 au rang de résidence royale. Quelques mois après l'abdication de Frédéric Ier le 18 janvier 1709, les cinq villes de Berlin, Cölln, Friedrichswerder, Dorotheenstadt et Friedrichstadt furent regroupées en une seule et même ville, Berlin, « capitale et résidence royale » (décret du 1er janvier 1710) : Königsberg, capitale de la Prusse historique, était ainsi finalement évincée, marquant un ancrage du royaume plus à l'ouest. Déjà, de nouveaux faubourgs commençaient à s'étendre aux portes de la nouvelle capitale.

Le fils de Frédéric, Frédéric-Guillaume Ier de Prusse, qui exerça seul le pouvoir à partir de 1713, était un prince frugal qui fit de la Prusse une puissance militaire de premier plan. Alors qu'en 1709, Berlin comptait 55 000 habitants, dont 5 000 servaient dans l'armée, dès 1755 elle pouvait s'enorgueillir de 100 000 habitants, dont 26 000 soldats. Frédéric-Guillaume fit en outre dresser alentour de la ville des barrières en bois percées de 14 portes, désignées par la suite sous le nom de barrière d'octroi de Berlin.

Frédéric II, surnommé Frédéric le Grand, fut couronné roi en 1740. On l'appelait aussi le roi-philosophe, car il s'était fait connaître par sa correspondance avec des écrivains comme Voltaire et d'Alembert. Berlin devint sous son règne l'un des centres de l'ère des Lumières. Le plus célèbre philosophe berlinois de l'époque était Moses Mendelssohn. La capitale prussienne ne fut toutefois pas épargnée par les guerres incessantes menées par Frédéric II pour conserver la Silésie. Lors de la guerre de Sept Ans, après une année 1759 catastrophique, les armées russes et autrichiennes occupèrent Berlin le 9 octobre 1760, avant que l'intervention providentielle du tsar Pierre III de Russie ne sauve la Prusse du désastre. En revanche, le règne du successeur de Frédéric II, Frédéric-Guillaume II reste dans l'histoire comme une période terne, le militarisme de l'État prussien l'emportant sur les activités commerciales et culturelles. Frédéric-Guillaume II était lui-même opposé aux Lumières : il exerça une censure moins subtile que son prédécesseur et pratiqua ouvertement la répression à l'occasion. En cette fin de XVIIIe siècle, il fit reconstruire les remparts de la ville, dont l'un des accès est la célébrissime porte de Brandebourg.

À l'issue des campagnes de la Quatrième Coalition, Napoléon Bonaparte fit une entrée triomphale à Berlin en 1806. L'occupation française marqua le début d'une ère de réformes visant à faire de la Prusse un État libéral, Berlin se voyant quant à elle dotée d'une administration autonome. Sous l'impulsion du ministre vom Stein, les premières élections du parlement berlinois, au suffrage censitaire, se tinrent en 1809. L'université de Berlin ouvrit ses portes en 1810, avec comme premier recteur le philosophe Johann Gottlieb Fichte. Les premiers journaux d'opinions, comme le Berliner Abendblätter d'Heinrich von Kleist, parurent à Berlin entre 1810 et 1811. À partir de 1812, les Juifs purent accéder à tous les emplois.

La révolution industrielle gagna les États allemands au cours de la première moitié du XIXe siècle, s'accompagnant d'un exode rural massif : la population de Berlin passa en quelques décennies de 200 000 à 400 000 habitants, la capitale de Prusse rejoignant Londres, Paris et Saint-Pétersbourg dans le peloton des quatre villes les plus peuplées d'Europe. La première ligne de chemin de fer de Prusse, la Berlin-Potsdamer Eisenbahn, entra en service le 22 septembre 1838, avec l'inauguration de la première gare berlinoise, la gare de Potsdam, située au sud-est de la Potsdamer Platz et qui marqua le début du développement rapide de l’Eisenbahnstadt Berlin. La ville devient le centre d'un important réseau ferroviaire, chaque ligne ayant toutefois sa propre gare-terminus : gare d'Anhalt (1841), gare de Stettin (1842), gare de Francfort (1842), gare de Hambourg (1846), gare de Görlitz (1866), gare de l'Est (1867), gare de Lehrte (1871), gare de Dresde (1875).

Guillaume Ier accéda au trône de Prusse en 1861. Les débuts de sa régence laissèrent espérer une libéralisation longtemps attendue dans le pays. Guillaume Ier nomma effectivement des ministres de réputation libérale et fit ériger le Rotes Rathaus, l'hôtel de ville de Berlin. L'agglomération de la capitale fut étendue administrativement en 1861 à de nouveaux faubourgs : Wedding, Moabit, Tempelhof et Schöneberg.

L’afflux de main-d’œuvre venant des campagnes vers Berlin depuis la suppression du servage fait rapidement augmenter la population si bien qu’entre 1860 et 1870 la population berlinoise passe de 493 000 à 826 000 habitants, faisant augmenter de près 50 % les loyers. Ce qui crée une grave crise du logement, plus de 70 000 Berlinois vivent dans la rue et beaucoup d’autres dans des maisons obscures et insalubres. Le centre commence à perdre peu à peu ses habitants au profit des bureaux, commerces, et administrations. Les limites de la ville sont repoussées pour englober les villages de Moabit, Gesundbrunnen, Wedding et une partie de Tempelhof et de Schoneberg qui deviennent des quartiers.

    </p>

    <h3>Capitale de l'Empire allemand
</h3>
    <p>Sous l'égide de la Prusse, les États d'Allemagne du Nord se fédérèrent à l'issue de la guerre de 1870 selon la « solution petite-allemande » ; l'Empire allemand fut proclamé au traité préliminaire de paix du 26 février 1871, avec le roi de Guillaume Ier de Prusse comme souverain, Otto von Bismarck comme chancelier et Berlin comme capitale.

Berlin était alors une cité industrielle de 800 000 habitants. Or, les infrastructures n'avaient pas suivi la croissance de la population. On entreprit enfin en 1873 la construction du réseau d'égout, qui fut parachevé en 1893. Au décollage économique de la révolution industrielle succéda le krach de 1873 consécutif à l'Unité allemande, une crise liée à l'apport massif de liquidités correspondant au paiement de l'indemnité de guerre française. L'extension urbaine demeura un sujet controversé. Le 1er janvier 1876, Berlin se vit confier par l'État les ponts et les boulevards de la ville. Signe des temps, les magistrats prussiens, lors du procès de Kreuzberg (1882), firent jurisprudence en donnant tort aux services d'urbanisme contre un particulier qui s'était vu refuser un permis de construire : le tribunal décida que l'État n'était compétent qu'en matière de sécurité publique, non en matière esthétique et paysagère. La préfecture de police de Berlin, fondée en 1809, était au début du XXe siècle un des plus importants services de police du monde.

Le réseau de chemin de fer national et régional fut réorganisé. En 1871 et 1877, le Ringbahn fut ouvert en deux étapes. Le Stadtbahn, qui traverse le centre de Berlin d'est en ouest, fut ouvert en 1882. Certaines gares redondantes furent fermées : gare de l'Est au profit de la gare de Francfort, qui devint alors gare de Silésie (1882) ; gare de Dresde au profit de la gare d'Anhalt et de Potsdam (1882) ; gare de Hambourg au profit de la gare de Lehrte (1884). Pour rééquilibrer la forte croissance du trafic en ville, la construction du métro de Berlin (U-Bahn) et des lignes de train de banlieue (S-Bahn) fut décidée en 1896. Dans les quartiers du centre-ville (Kreuzberg, Prenzlauer Berg, Friedrichshain et Wedding), regroupés sous le terme de « Wilhelminischer Ring (de) », les autorités firent construire des logements sociaux pour permettre le logement des ouvriers. Tandis qu'au sud-ouest de Berlin, une banlieue pavillonnaire compacte et très étendue s'était développée depuis 1850, de nouveaux quartiers bourgeois virent le jour à l'ouest à la fin du XIXe siècle. Entre 1904 et 1908, une collection de guides intitulés Großstadt-Dokumente (51 numéros) se consacrait exclusivement à la vie berlinoise. Un pont-aux-ânes de la recherche en urbanisme dans les pays germanophones à la Belle Époque était l'opposition de la ville tentaculaire qu'était Berlin à Vienne, ville d'histoire et de culture. Le premier aérodrome d'Allemagne ouvrit en 1909 à Johannisthal. En 1911, l'association « Zweckverband Groß-Berlin » se donna pour tâche de coordonner le développement des services dans une ville à la croissance explosive. Elle obtient en 1920 la création de la communauté urbaine du « Grand Berlin » (Gross-Berlin) ; une autre conception, toujours actuelle, de cette association est celle de coulée verte.

La Première Guerre mondiale provoqua la famine à Berlin. Au cours de l'hiver 1916 – 17, on dénombrait déjà 150 000 personnes souffrant de faim, et les grèves commençaient à se multiplier. Lorsque l'armistice fut signé à la fin de 1918, l'empereur Guillaume II abdiqua. À l'issue de la révolution de novembre, le socialiste Philipp Scheidemann et le communiste Karl Liebknecht appelèrent à la république. Dans les semaines qui suivirent, Berlin fut le théâtre de multiples émeutes de rues opposant spartakistes et corps francs, et qui s'achevèrent par l'écrasement du soulèvement spartakiste.

    </p>
    <h3>La république de Weimar
</h3>
<p>Le Parti communiste d'Allemagne (Kommunistische Partei Deutschlands ou KPD) fut fondé à Berlin à la fin de décembre 1918. Il essaya de mettre en place un pouvoir des conseils ouvriers au mois de janvier 1919, mais l'exemple du pouvoir bolchevik russe avait déjà effrayé et mobilisé non seulement la droite, mais aussi des socialistes comme Friedrich Ebert. La révolution spartakiste échoua, et l'armée loyaliste exécuta le 15 janvier les deux meneurs, Rosa Luxemburg et Karl Liebknecht. En mars 1920, c'était au tour du Parti des Patriotes allemands (Deutsche Vaterlandspartei) mené par Wolfgang Kapp, de tenter de renverser le gouvernement. Les garnisons de Berlin se joignirent cette fois aux émeutiers, et les palais gouvernementaux furent occupés (le gouvernement de la République de Weimar avait déjà quitté la capitale). Mais une grève générale mit un terme au coup d’État.

Le Grand Berlin (Gross-Berlin) fut instauré par la loi du 1er octobre 1920. L'ancienne ville de Berlin (66 km ²) se trouva ainsi agrandie par l'annexion de sept villes avoisinantes (Charlottenbourg, Köpenick, Lichtenberg, Neukölln, Schöneberg, Spandau et Wilmersdorf), 59 communes et 27 districts ruraux, le tout divisé en 20 districts et s'étalant sur une superficie de 883 km ². La nouvelle ville de Berlin ainsi créée représentait alors 3 804 048 habitants.

En 1922, le ministre des Affaires étrangères Walther Rathenau fut assassiné à Berlin. La ville fut en état de choc, et près d'un demi-million de citadins défilèrent à son enterrement.

La situation économique était catastrophique. Le traité de Versailles condamnait l'Allemagne à verser de lourdes réparations de guerre. À la suite de l'occupation de la Ruhr par les troupes françaises et belges, le gouvernement fit tourner la planche à billets. Cette pratique, qui se superposait à une économie déprimée, conduisit à une hyperinflation, supportée principalement par les prolétaires, les salariés et les petits rentiers. La situation commença à s'améliorer à partir de 1924 à la suite d'une renégociation avec les Alliés, des fonds d'aide américains ainsi que d'une politique financière plus rigoureuse. C'était le début des Années folles à Berlin, une période faste appelée en allemand « die Goldene Zwanziger (de) ». Berlin devint la plus grande ville industrielle d'Europe.

Grâce à des personnalités comme l'architecte Walter Gropius, le physicien Albert Einstein, le peintre George Grosz, les écrivains Arnold Zweig, Bertolt Brecht et Kurt Tucholsky, et des acteurs et cinéastes comme Marlene Dietrich, Friedrich Wilhelm Murnau et Fritz Lang, Berlin faisait figure de grand centre culturel en Europe, sans éclipser pour autant l'hégémonie parisienne.

L'aéroport de Tempelhof fut inauguré en 1924. Cette même année, le salon international de la radiodiffusion de Berlin, un des plus anciens salons industriels d'Allemagne, se tint pour la première fois au Parc des expositions de Berlin (Messegelände). Berlin était le second plus grand port fluvial du pays. Les lignes ferroviaires de métro, de banlieue et de ceinture, électrifiées depuis 1924, furent fédérées en 1930 sous le nom de S-Bahn. Cette infrastructure était devenue indispensable à une population de 4 millions d'habitants. À l'occasion du 3e Salon international de la radiophonie en 1926, on inaugura la Berliner Funkturm. De 1930 à 1933, l'Association Aérospatiale, dont le futur ingénieur Wernher von Braun était membre, procéda aux premiers essais de tirs de fusées sur la Raketenflugplatz (de) de Berlin dans le faubourg nord de Tegel.

Cette courte période de prospérité prit fin avec la crise économique de 1929. Le Parti nazi d'Adolf Hitler remporta ses premiers sièges au parlement. Le gouvernement régional prussien dirigé par Otto Braun fut déposé le 20 juillet 1932 lors d'un coup d'État, le Preussenschlag : la république commençait à céder sous les coups conjugués des menées extrémistes de droite et de gauche.
</p>
<h3>Le Troisième Reich
</h3>
<p>Son parti ayant remporté les nouvelles élections législatives, Hitler fut finalement choisi comme chancelier par le président von Hindenburg le 30 janvier 1933. Le palais du Reichstag fut incendié le 27 février 1933. Les mesures drastiques du nouveau gouvernement nazi suspendirent le fonctionnement des institutions démocratiques de la république de Weimar.

Il y avait à Berlin en 1933 environ 160 000 Juifs, soit un tiers des Juifs d'Allemagne, et 4 % de la population de l'agglomération. Un tiers d'entre eux était des immigrants d'Europe de l'Est, massés dans le quartier du Scheunen près de l’Alexanderplatz. Principale cible du nouveau régime, ils durent renoncer aux emplois les plus prestigieux : dès mars 1933, tous les médecins juifs exerçant à l'hôpital « La Charité » durent démissionner. Pendant la première semaine d'avril, les militants nazis organisèrent le « boycott des Juifs », empêchant les Berlinois de fréquenter les magasins tenus par des Juifs.

Les Jeux olympiques d'été de 1936 devaient se tenir dans la capitale. Les nazis reprirent à leur compte cette décision, rappelant que les Jeux de 1916, qui auraient dû se tenir à Berlin, avaient été annulés pour cause de guerre. Pour ne pas isoler politiquement Berlin des autres grandes capitales, ils procédèrent à une mise en scène consistant à supprimer momentanément les panneaux d'interdiction et de proscription anti-juifs, tels les affiches « Für Juden verboten » (« Interdit aux Juifs »). Le jubilé des 700 ans de Berlin, l'année suivante, permit à nouveau à la propagande nazie de s'exprimer en ville. Lors de la nuit de Cristal du 9 au 10 novembre 1938, un pogrom national entraîna l'incendie des synagogues, la destruction des magasins et des maisons habitées par des Juifs, et de nombreuses arrestations. En 1939, il y avait encore 75 000 Juifs vivant à Berlin. Le 18 octobre 1941, le premier d'une série de 63 convois quitta de la gare de Grünewald, transportant des Juifs jusqu'au ghetto de Łódź, marquant le début de la « Solution finale ». On déporta dans ce camp de concentration 50 000 personnes, la plupart pour y être exécutées. Le quartier de Wannsee fut le siège de la conférence de 1942 prononcée par le chef de l'Office central de la Sécurité du Reich, le SS Reinhard Heydrich, fixant l'organisation de la Solution finale. Un peu plus de 1 200 Juifs parvinrent à survivre en cachette à Berlin, grâce à l'action de quelques justes.

Berlin, année zéro. Après la prise de la ville par l'armée rouge en mai, état des rues en juillet 1945. La nation est brisée, ses élites politiques et culturelles ont disparu, ses hommes en armes démobilisés. Ne restent que les femmes allemandes pour retirer les décombres.
Sur le plan de l'urbanisme, les nazis cherchaient également à donner au Grand Reich une capitale à sa mesure, et imaginèrent de transformer Berlin en une nouvelle capitale mondiale, Welthauptstadt Germania dans le style colossal. Les constructions devaient s'étaler de 1938 à 1950. Selon les plans de l'architecte officiel Albert Speer, il s'agissait, en faisant au besoin disparaître les quartiers historiques de la ville, de percer la ville de boulevards rectilignes de largeur démesurée (pour les défilés), ponctués par des édifices monumentaux. Au centre était prévu le « grand pavillon du peuple », une gigantesque halle destinée à accueillir les discours du Führer avec une coupole de cuivre d'une hauteur totale de 280 mètres. L'édifice aurait écrasé de son volume le Reichstag à ses pieds. Tout autour de ce noyau gouvernemental, des autoroutes devaient donner à Germania une touche moderne. Pour le projet Germania,[réf. nécessaire] des milliers de Juifs berlinois furent expropriés afin d'attribuer leurs appartements aux habitants délogés par les travaux de destruction préalables. Des milliers de travailleurs forcés furent transportés à Berlin depuis des camps de concentration. Quoique la plupart de ces projets n'aient pas vu le jour du fait de la guerre et des restrictions économiques, il subsiste des vestiges des premières constructions de Speer, que l'on peut encore voir aujourd'hui. Une exposition leur a été récemment consacrée.

Berlin devient durant la Seconde Guerre mondiale une cible prioritaire des bombardements alliés. La bataille de Berlin avec les forces soviétiques est acharnée et les dégâts sont considérables : de 1939 à 1945, la population chute de 4,3 à 2,8 millions d'habitants ; la ville est en grande partie détruite, le centre-ville un désert de ruines, débarrassées par les « femmes des ruines ».

Cependant Berlin n'est pas, contrairement à une idée reçue, la ville la plus détruite d'Allemagne. En 1945, 20 % des logements sont dits « inhabitables », ce qui est un taux relativement faible par rapport à d'autres cibles de l'aviation britannique, comme Hambourg, Dresde, Francfort ou Cologne. Les bombardements alliés se sont concentrés sur les quartiers centraux, mais ont épargné volontairement des zones proches des aéroports que l'on souhaitait utiliser après la fin des hostilités. De plus, la faible densité de Berlin (moins de la moitié de celle de Paris), la largeur des boulevards, les nombreux espaces verts ont empêché de nombreuses munitions d'atteindre un objectif. Enfin les bombardements alliés les plus meurtriers et les plus destructeurs furent ceux de Hambourg et de Dresde, du fait de techniques mixtes, mêlant explosifs et torches incendiaires, aux effets combinés dévastateurs. Ces formules n'ont jamais réussi à Berlin.

À l'issue de la conférence de Yalta, tenue du 4 au 11 février 1945, les Alliés s'accordèrent pour diviser non seulement l'Allemagne en quatre zones d'occupation, mais également l'ancienne capitale du Reich, Berlin : les quatre puissances occupantes, responsables chacune d'un secteur, seraient : les États-Unis, le Royaume-Uni, la France, et l'Union des républiques socialistes soviétiques. Les forces soviétiques évacuèrent donc pendant l'été 1945 les quartiers ouest de Berlin, où elles avaient combattu les derniers nids de résistance nazie au printemps, et cela bien qu'encore au mois de mai, elles eussent investi un premier magistrat en la personne d’Arthur Werner ainsi qu'un gouvernement provisoire composé d'anciens membres du KPD allemand dissout.

Les premières élections municipales du Grand Berlin se tinrent le 20 octobre 1946 dans les quatre secteurs d'occupation et se soldèrent par une nette victoire du SPD (48,7%) devant la CDU (22,2%) et le SED (19,8%) communiste. Il s'ensuivit une opposition politique croissante tant dans l'administration quotidienne de la ville que dans les délibérations du conseil municipal, allant jusqu'à des émeutes et des occupations de locaux dans les secteurs ouest, une agitation probablement alimentée par les communistes, bien que désavouée officiellement par les élus du SED.

Malgré la division officielle de Berlin en quatre zones, les américains et les britanniques optèrent (1er janvier 1947) pour un gouvernement unique des deux secteurs sous leur responsabilité : la Bizone. En protestation contre ce que les soviétiques considéraient comme une remise en cause des accords, le maréchal Vassili Sokolovski se retire le 20 mars 1948 du conseil de contrôle interallié. Les désaccords politiques entre les Alliés et l'Union soviétique continuèrent de s'envenimer, jusqu'au Blocus de Berlin par les soviétiques (juin 1948), ce qui incita la France à rejoindre la création de la Trizone au 1er août 1948, qui aboutira un an plus tard (23 mai 1949) à la création d'un nouvel État allemand, la RFA ; enfin la proclamation unilatérale d'une réforme monétaire dans les secteurs ouest, qui s'ensuivit d'un afflux de reichsmarks dévalorisés dans la zone d'occupation soviétique, sont autant d'initiatives que les autorités soviétiques interprétèrent comme des entorses aux accords de Yalta et à la conférence de Potsdam, qui garantissait le principe de l’unité de l’Allemagne.

À partir de ce jour, la ville de Berlin se retrouva alors définitivement divisée en deux tant politiquement qu'administrativement, avec deux municipalités concurrentes : Berlin-Ouest et Berlin-Est
</p>
<h3>Berlin et la fondation des deux Allemagnes
</h3>
<p>La loi constitutionnelle du 23 mai 1949 qui créait la République fédérale d’Allemagne à partir des trois zones d'occupation américaine, britannique et française, faisait par son article 23 du Grand Berlin un Land fédéral. Le 7 octobre suivant, une loi analogue créait la République démocratique allemande : la rédaction originale de ce dernier texte qualifiait l'Allemagne de « république indivisible », en ce sens qu'il n'y aurait qu'une nation allemande dont la capitale serait Berlin. Dans l'esprit des auteurs de ce texte, Berlin signifiait ici aussi le Grand Berlin, puisque, selon le point de vue est-allemand, tout le territoire de l'agglomération se trouvait en zone d'occupation soviétique, les secteurs ouest étant simplement administrés par les forces de l'OTAN… Ainsi les deux nouveaux États revendiquaient Berlin en totalité, sans jamais parvenir à exercer leur autorité sur toute l'agglomération avant le 3 octobre 1990.

La constitution fut appliquée en 1950 à Berlin-Ouest. Au terme de l'article 2 alinéa 1er de la constitution, Berlin était donc jusqu'en 1990 un Land de la République fédérale allemande, mais cet article resta sans effet, les forces occupantes de Berlin-Ouest en ayant reporté l'application. Les premières élections législatives eurent lieu à Berlin-Ouest le 3 décembre 1950.
</p>
<h3>La construction du Mur
</h3>
<p>Au cours de l'automne 1958, plusieurs responsables politiques du bloc soviétique (Walter Ulbricht, Khrouchtchev, Gomulka) remirent publiquement en cause le statut international de Berlin. À l'unisson, la presse communiste européenne entama à son tour une campagne dans ce sens, si bien que le 27 novembre 1958, le secrétaire général du Parti communiste soviétique, Nikita Khrouchtchev, expédia une note aux trois occupants occidentaux ainsi qu'au gouvernement de la République fédérale allemande.

Lassées de l'exode ininterrompu des Allemands vers la RFA via les secteurs d'occupation ouest, les autorités est-allemandes, avec l'aval des Soviétiques, arrêtèrent la décision de séparer physiquement « Berlin-Est » et « Berlin-Ouest » par une muraille surveillée par un réseau de miradors. La construction du mur commença dans la nuit du 12 au 13 août 1961.

Dès lors, et jusqu'à la chute du Mur le 9 novembre 1989, chaque moitié de Berlin se veut une vitrine idéologique de son camp. Berlin-Est est la capitale choyée de la RDA (grandes réalisations architecturales plus ou moins heureuses, vie culturelle dense et relativement libre), tandis que Berlin-Ouest est une île capitaliste et libertaire au milieu du bloc soviétique subventionnée par la RFA qui attire nombre d'artistes.

Tandis que Berlin-Ouest se restructurait autour du Kurfürstendamm, Berlin-Est érigeait l'Alexanderplatz en nouveau centre-ville. La moitié ouest se dota dès 1948 d'un établissement d'enseignement supérieur propre avec l'université libre de Berlin (Berlin-Est se chargeant de rouvrir la vénérable université Humboldt). Parmi les autres projets significatifs qui virent le jour à l'ouest, la rocade autoroutière, la Philharmonie de Berlin, l'Europa-Center et le nouvel opéra. Au cours des années 1970, les autorités est-allemandes reconstruisirent d'anciens quartiers en lançant un vaste programme de construction de logements à loyers modérés.
</p>
<h3>Chute du Mur et réunification allemande
</h3>
<p>Au mois d'octobre 1989, lors des festivités commémorant à Berlin-Est le 40e anniversaire de la RDA, l'invité d'honneur, Mikhaïl Gorbatchev, prononça un discours dans lequel il laissait entendre qu'il ne soutiendrait plus la politique répressive que le gouvernement de la RDA pratiquait à l'encontre des transfuges, lesquels à cette époque fuyaient le pays via la Hongrie et la Tchécoslovaquie. Le 9 novembre, les gardes-frontière de la Bornholmer Strasse, abusés par une interprétation incorrecte d'une allocution de Günter Schabowski, membre du Politbüro du Parti socialiste unifié d'Allemagne, laissèrent le passage à la foule qui s'était massée devant eux : ils croyaient que le Politbüro avait décidé l'ouverture des frontières, bien qu'aucune décision n'eût réellement été prise à ce sujet. Depuis la démission du chef du Parti socialiste Erich Honecker au mois d'octobre, les autorités de RDA étaient livrées à elles-mêmes.

Près de la porte de Brandebourg, plusieurs Berlinois grimpèrent sur le Mur et dansèrent dessus. Cette fois, il n'y eut plus d'intervention de blindés. Le Mur était franchissable et fut bientôt démantelé ici et là, plusieurs habitants empoignant marteau et burin pour détacher des éclats de ciment du mur, afin d'en faire des souvenirs : ces collectionneurs furent appelés Mauerspechte.

Le 3 octobre 1990, l'Allemagne, et Berlin avec elle, était réunifiée. Par la reconnaissance du traité de réunification, les Alliés renoncèrent à leurs droits sur un Berlin qui n'était jusque-là qu'un territoire de la RFA. Il s'ensuivit le 2 décembre les premières élections des conseillers municipaux de Berlin réunifiée. Au travers de l'Hauptstadtbeschluss, Berlin devint en 1991 la capitale fédérale de la République fédérale d'Allemagne, grâce à une courte majorité au Bundestag lors du vote du 20 juin 1991 (337 contre 320 votes)17. Le 7 septembre 1999, le Bundestag s'établit à Berlin, suivi le 29 septembre 2000 par le Bundesrat.

Depuis la réunification, l'interruption de la plupart des subventions des Länder et, depuis 1997, le scandale de la Société bancaire de Berlin (de), ont mis la ville et le Land de Berlin dans d'énormes difficultés financières, lesquelles limitent la capacité d'investissement des autorités. Berlin plaide depuis devant le Tribunal constitutionnel fédéral le surendettement, pour obtenir une contribution complémentaire de 35 milliards d'euros en vue de réduire la dette. Ces circonstances ont conduit à un vote de désaveu en 2001 à l'encontre du maire en exercice, Eberhard Diepgen. Son successeur, Klaus Wowereit, fut élu par une assemblée de majorité SPD-Grünen et avec l'abstention du PDS. Après l'échec des négociations pour une « grande coalition », la réélection de la chambre des députés, le 21 octobre 2001, a conduit à un gouvernement d'union de la gauche.

La plupart des monuments importants, endommagés depuis la guerre, ont été reconstruits ou restaurés, surtout depuis 1989, la plus grande partie du patrimoine historique se trouvant jusqu'alors à Berlin-Est. Ainsi, à l'instar de Munich, le visage actuel de Berlin a bien moins changé par rapport à l'avant-guerre que celui d'autres villes allemandes.
</p>
</div>
</div>
    <script src="js/lightbox-plus-jquery.js"></script>
</body>
